'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9043
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9043.
'
Namespace SessionHeaderPage
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SessionHeaderPage_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/sessionheaderpage")>  _
    Partial Public Class SessionHeaderPage_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.1.100.22:7047/ABRWEB/WS/Bsat%20Supermarket%20S.A.L/Page/SessionHeaderPa"& _ 
                "ge"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal ID As String, ByVal User_ID As String, ByVal Store_No As String, ByVal Device_ID As String) As <System.Xml.Serialization.XmlElementAttribute("SessionHeaderPage")> SessionHeaderPage
            Dim results() As Object = Me.Invoke("Read", New Object() {ID, User_ID, Store_No, Device_ID})
            Return CType(results(0),SessionHeaderPage)
        End Function
        
        '''<remarks/>
        Public Function BeginRead(ByVal ID As String, ByVal User_ID As String, ByVal Store_No As String, ByVal Device_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Read", New Object() {ID, User_ID, Store_No, Device_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRead(ByVal asyncResult As System.IAsyncResult) As SessionHeaderPage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SessionHeaderPage)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("SessionHeaderPage")> SessionHeaderPage
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),SessionHeaderPage)
        End Function
        
        '''<remarks/>
        Public Function BeginReadByRecId(ByVal recId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReadByRecId", New Object() {recId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndReadByRecId(ByVal asyncResult As System.IAsyncResult) As SessionHeaderPage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SessionHeaderPage)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As SessionHeaderPage_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> SessionHeaderPage()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),SessionHeaderPage())
        End Function
        
        '''<remarks/>
        Public Function BeginReadMultiple(ByVal filter() As SessionHeaderPage_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndReadMultiple(ByVal asyncResult As System.IAsyncResult) As SessionHeaderPage()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SessionHeaderPage())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginIsUpdated(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("IsUpdated", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndIsUpdated(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetRecIdFromKey(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetRecIdFromKey", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetRecIdFromKey(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:Create", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="Create_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Create(ByRef SessionHeaderPage As SessionHeaderPage)
            Dim results() As Object = Me.Invoke("Create", New Object() {SessionHeaderPage})
            SessionHeaderPage = CType(results(0),SessionHeaderPage)
        End Sub
        
        '''<remarks/>
        Public Function BeginCreate(ByVal SessionHeaderPage As SessionHeaderPage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Create", New Object() {SessionHeaderPage}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndCreate(ByVal asyncResult As System.IAsyncResult, ByRef SessionHeaderPage As SessionHeaderPage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            SessionHeaderPage = CType(results(0),SessionHeaderPage)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:CreateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="CreateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef SessionHeaderPage_List() As SessionHeaderPage)
            Dim results() As Object = Me.Invoke("CreateMultiple", New Object() {SessionHeaderPage_List})
            SessionHeaderPage_List = CType(results(0),SessionHeaderPage())
        End Sub
        
        '''<remarks/>
        Public Function BeginCreateMultiple(ByVal SessionHeaderPage_List() As SessionHeaderPage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateMultiple", New Object() {SessionHeaderPage_List}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndCreateMultiple(ByVal asyncResult As System.IAsyncResult, ByRef SessionHeaderPage_List() As SessionHeaderPage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            SessionHeaderPage_List = CType(results(0),SessionHeaderPage())
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef SessionHeaderPage As SessionHeaderPage)
            Dim results() As Object = Me.Invoke("Update", New Object() {SessionHeaderPage})
            SessionHeaderPage = CType(results(0),SessionHeaderPage)
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdate(ByVal SessionHeaderPage As SessionHeaderPage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Update", New Object() {SessionHeaderPage}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdate(ByVal asyncResult As System.IAsyncResult, ByRef SessionHeaderPage As SessionHeaderPage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            SessionHeaderPage = CType(results(0),SessionHeaderPage)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef SessionHeaderPage_List() As SessionHeaderPage)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {SessionHeaderPage_List})
            SessionHeaderPage_List = CType(results(0),SessionHeaderPage())
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateMultiple(ByVal SessionHeaderPage_List() As SessionHeaderPage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateMultiple", New Object() {SessionHeaderPage_List}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateMultiple(ByVal asyncResult As System.IAsyncResult, ByRef SessionHeaderPage_List() As SessionHeaderPage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            SessionHeaderPage_List = CType(results(0),SessionHeaderPage())
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionheaderpage:Delete", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", ResponseElementName:="Delete_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginDelete(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Delete", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndDelete(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/sessionheaderpage")>  _
    Partial Public Class SessionHeaderPage
        
        Private keyField As String
        
        Private idField As String
        
        Private user_IDField As String
        
        Private store_NoField As String
        
        Private device_IDField As String
        
        Private type_Of_TransactionField As Type_Of_Transaction
        
        Private type_Of_TransactionFieldSpecified As Boolean
        
        Private dateField As Date
        
        Private dateFieldSpecified As Boolean
        
        Private label_CodeField As String
        
        Private brand_NameField As Brand_Name
        
        Private brand_NameFieldSpecified As Boolean
        
        Private printedField As Boolean
        
        Private printedFieldSpecified As Boolean
        
        Private pricing_Job_NoField As String
        
        Private no_of_LinesField As Integer
        
        Private no_of_LinesFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property User_ID() As String
            Get
                Return Me.user_IDField
            End Get
            Set
                Me.user_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Store_No() As String
            Get
                Return Me.store_NoField
            End Get
            Set
                Me.store_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Device_ID() As String
            Get
                Return Me.device_IDField
            End Get
            Set
                Me.device_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type_Of_Transaction() As Type_Of_Transaction
            Get
                Return Me.type_Of_TransactionField
            End Get
            Set
                Me.type_Of_TransactionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Type_Of_TransactionSpecified() As Boolean
            Get
                Return Me.type_Of_TransactionFieldSpecified
            End Get
            Set
                Me.type_Of_TransactionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DateSpecified() As Boolean
            Get
                Return Me.dateFieldSpecified
            End Get
            Set
                Me.dateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Label_Code() As String
            Get
                Return Me.label_CodeField
            End Get
            Set
                Me.label_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Brand_Name() As Brand_Name
            Get
                Return Me.brand_NameField
            End Get
            Set
                Me.brand_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Brand_NameSpecified() As Boolean
            Get
                Return Me.brand_NameFieldSpecified
            End Get
            Set
                Me.brand_NameFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Printed() As Boolean
            Get
                Return Me.printedField
            End Get
            Set
                Me.printedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PrintedSpecified() As Boolean
            Get
                Return Me.printedFieldSpecified
            End Get
            Set
                Me.printedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pricing_Job_No() As String
            Get
                Return Me.pricing_Job_NoField
            End Get
            Set
                Me.pricing_Job_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property No_of_Lines() As Integer
            Get
                Return Me.no_of_LinesField
            End Get
            Set
                Me.no_of_LinesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property No_of_LinesSpecified() As Boolean
            Get
                Return Me.no_of_LinesFieldSpecified
            End Get
            Set
                Me.no_of_LinesFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/sessionheaderpage")>  _
    Public Enum Type_Of_Transaction
        
        '''<remarks/>
        Shelf
        
        '''<remarks/>
        Item
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/sessionheaderpage")>  _
    Public Enum Brand_Name
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Redy
        
        '''<remarks/>
        Bsat
    End Enum
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/sessionheaderpage")>  _
    Partial Public Class SessionHeaderPage_Filter
        
        Private fieldField As SessionHeaderPage_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As SessionHeaderPage_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/sessionheaderpage")>  _
    Public Enum SessionHeaderPage_Fields
        
        '''<remarks/>
        ID
        
        '''<remarks/>
        User_ID
        
        '''<remarks/>
        Store_No
        
        '''<remarks/>
        Device_ID
        
        '''<remarks/>
        Type_Of_Transaction
        
        '''<remarks/>
        [Date]
        
        '''<remarks/>
        Label_Code
        
        '''<remarks/>
        Brand_Name
        
        '''<remarks/>
        Printed
        
        '''<remarks/>
        Pricing_Job_No
        
        '''<remarks/>
        No_of_Lines
    End Enum
End Namespace
