'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9043
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9043.
'
Namespace SessionLabelLinePage
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SessionLabelLinePage_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage")>  _
    Partial Public Class SessionLabelLinePage_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.1.100.22:7047/ABRWEB/WS/Bsat%20Supermarket%20S.A.L/Page/SessionLabelLin"& _ 
                "ePage"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal Session_ID As String, ByVal User_ID As String, ByVal Store_No As String, ByVal Device_ID As String, ByVal Line_No As Integer) As <System.Xml.Serialization.XmlElementAttribute("SessionLabelLinePage")> SessionLabelLinePage
            Dim results() As Object = Me.Invoke("Read", New Object() {Session_ID, User_ID, Store_No, Device_ID, Line_No})
            Return CType(results(0),SessionLabelLinePage)
        End Function
        
        '''<remarks/>
        Public Function BeginRead(ByVal Session_ID As String, ByVal User_ID As String, ByVal Store_No As String, ByVal Device_ID As String, ByVal Line_No As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Read", New Object() {Session_ID, User_ID, Store_No, Device_ID, Line_No}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRead(ByVal asyncResult As System.IAsyncResult) As SessionLabelLinePage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SessionLabelLinePage)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("SessionLabelLinePage")> SessionLabelLinePage
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),SessionLabelLinePage)
        End Function
        
        '''<remarks/>
        Public Function BeginReadByRecId(ByVal recId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReadByRecId", New Object() {recId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndReadByRecId(ByVal asyncResult As System.IAsyncResult) As SessionLabelLinePage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SessionLabelLinePage)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As SessionLabelLinePage_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> SessionLabelLinePage()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),SessionLabelLinePage())
        End Function
        
        '''<remarks/>
        Public Function BeginReadMultiple(ByVal filter() As SessionLabelLinePage_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndReadMultiple(ByVal asyncResult As System.IAsyncResult) As SessionLabelLinePage()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SessionLabelLinePage())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginIsUpdated(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("IsUpdated", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndIsUpdated(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetRecIdFromKey(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetRecIdFromKey", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetRecIdFromKey(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:Create", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="Create_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Create(ByRef SessionLabelLinePage As SessionLabelLinePage)
            Dim results() As Object = Me.Invoke("Create", New Object() {SessionLabelLinePage})
            SessionLabelLinePage = CType(results(0),SessionLabelLinePage)
        End Sub
        
        '''<remarks/>
        Public Function BeginCreate(ByVal SessionLabelLinePage As SessionLabelLinePage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Create", New Object() {SessionLabelLinePage}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndCreate(ByVal asyncResult As System.IAsyncResult, ByRef SessionLabelLinePage As SessionLabelLinePage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            SessionLabelLinePage = CType(results(0),SessionLabelLinePage)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:CreateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="CreateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef SessionLabelLinePage_List() As SessionLabelLinePage)
            Dim results() As Object = Me.Invoke("CreateMultiple", New Object() {SessionLabelLinePage_List})
            SessionLabelLinePage_List = CType(results(0),SessionLabelLinePage())
        End Sub
        
        '''<remarks/>
        Public Function BeginCreateMultiple(ByVal SessionLabelLinePage_List() As SessionLabelLinePage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateMultiple", New Object() {SessionLabelLinePage_List}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndCreateMultiple(ByVal asyncResult As System.IAsyncResult, ByRef SessionLabelLinePage_List() As SessionLabelLinePage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            SessionLabelLinePage_List = CType(results(0),SessionLabelLinePage())
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef SessionLabelLinePage As SessionLabelLinePage)
            Dim results() As Object = Me.Invoke("Update", New Object() {SessionLabelLinePage})
            SessionLabelLinePage = CType(results(0),SessionLabelLinePage)
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdate(ByVal SessionLabelLinePage As SessionLabelLinePage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Update", New Object() {SessionLabelLinePage}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdate(ByVal asyncResult As System.IAsyncResult, ByRef SessionLabelLinePage As SessionLabelLinePage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            SessionLabelLinePage = CType(results(0),SessionLabelLinePage)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef SessionLabelLinePage_List() As SessionLabelLinePage)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {SessionLabelLinePage_List})
            SessionLabelLinePage_List = CType(results(0),SessionLabelLinePage())
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateMultiple(ByVal SessionLabelLinePage_List() As SessionLabelLinePage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateMultiple", New Object() {SessionLabelLinePage_List}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateMultiple(ByVal asyncResult As System.IAsyncResult, ByRef SessionLabelLinePage_List() As SessionLabelLinePage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            SessionLabelLinePage_List = CType(results(0),SessionLabelLinePage())
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/sessionlabellinepage:Delete", RequestNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", ResponseElementName:="Delete_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginDelete(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Delete", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndDelete(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage")>  _
    Partial Public Class SessionLabelLinePage
        
        Private keyField As String
        
        Private session_IDField As String
        
        Private user_IDField As String
        
        Private store_NoField As String
        
        Private device_IDField As String
        
        Private line_NoField As Integer
        
        Private line_NoFieldSpecified As Boolean
        
        Private label_CodeField As String
        
        Private barcode_NoField As String
        
        Private descriptionField As String
        
        Private quantityField As Integer
        
        Private quantityFieldSpecified As Boolean
        
        Private item_NoField As String
        
        Private unit_Of_MeasureField As String
        
        Private variantField As String
        
        Private text_1Field As String
        
        Private text_2Field As String
        
        Private text_3Field As String
        
        Private packed_DateField As Date
        
        Private packed_DateFieldSpecified As Boolean
        
        Private expiry_DateField As Date
        
        Private expiry_DateFieldSpecified As Boolean
        
        Private time_ScannedField As Date
        
        Private time_ScannedFieldSpecified As Boolean
        
        Private printedField As Boolean
        
        Private printedFieldSpecified As Boolean
        
        Private date_Last_PrintedField As Date
        
        Private date_Last_PrintedFieldSpecified As Boolean
        
        Private time_Last_PrintedField As Date
        
        Private time_Last_PrintedFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Session_ID() As String
            Get
                Return Me.session_IDField
            End Get
            Set
                Me.session_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property User_ID() As String
            Get
                Return Me.user_IDField
            End Get
            Set
                Me.user_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Store_No() As String
            Get
                Return Me.store_NoField
            End Get
            Set
                Me.store_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Device_ID() As String
            Get
                Return Me.device_IDField
            End Get
            Set
                Me.device_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Line_No() As Integer
            Get
                Return Me.line_NoField
            End Get
            Set
                Me.line_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Line_NoSpecified() As Boolean
            Get
                Return Me.line_NoFieldSpecified
            End Get
            Set
                Me.line_NoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Label_Code() As String
            Get
                Return Me.label_CodeField
            End Get
            Set
                Me.label_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Barcode_No() As String
            Get
                Return Me.barcode_NoField
            End Get
            Set
                Me.barcode_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity() As Integer
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QuantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Item_No() As String
            Get
                Return Me.item_NoField
            End Get
            Set
                Me.item_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Unit_Of_Measure() As String
            Get
                Return Me.unit_Of_MeasureField
            End Get
            Set
                Me.unit_Of_MeasureField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Variant]() As String
            Get
                Return Me.variantField
            End Get
            Set
                Me.variantField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Text_1() As String
            Get
                Return Me.text_1Field
            End Get
            Set
                Me.text_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Text_2() As String
            Get
                Return Me.text_2Field
            End Get
            Set
                Me.text_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Text_3() As String
            Get
                Return Me.text_3Field
            End Get
            Set
                Me.text_3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Packed_Date() As Date
            Get
                Return Me.packed_DateField
            End Get
            Set
                Me.packed_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Packed_DateSpecified() As Boolean
            Get
                Return Me.packed_DateFieldSpecified
            End Get
            Set
                Me.packed_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Expiry_Date() As Date
            Get
                Return Me.expiry_DateField
            End Get
            Set
                Me.expiry_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Expiry_DateSpecified() As Boolean
            Get
                Return Me.expiry_DateFieldSpecified
            End Get
            Set
                Me.expiry_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Time_Scanned() As Date
            Get
                Return Me.time_ScannedField
            End Get
            Set
                Me.time_ScannedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Time_ScannedSpecified() As Boolean
            Get
                Return Me.time_ScannedFieldSpecified
            End Get
            Set
                Me.time_ScannedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Printed() As Boolean
            Get
                Return Me.printedField
            End Get
            Set
                Me.printedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PrintedSpecified() As Boolean
            Get
                Return Me.printedFieldSpecified
            End Get
            Set
                Me.printedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Date_Last_Printed() As Date
            Get
                Return Me.date_Last_PrintedField
            End Get
            Set
                Me.date_Last_PrintedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Date_Last_PrintedSpecified() As Boolean
            Get
                Return Me.date_Last_PrintedFieldSpecified
            End Get
            Set
                Me.date_Last_PrintedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="time")>  _
        Public Property Time_Last_Printed() As Date
            Get
                Return Me.time_Last_PrintedField
            End Get
            Set
                Me.time_Last_PrintedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Time_Last_PrintedSpecified() As Boolean
            Get
                Return Me.time_Last_PrintedFieldSpecified
            End Get
            Set
                Me.time_Last_PrintedFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage")>  _
    Partial Public Class SessionLabelLinePage_Filter
        
        Private fieldField As SessionLabelLinePage_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As SessionLabelLinePage_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/sessionlabellinepage")>  _
    Public Enum SessionLabelLinePage_Fields
        
        '''<remarks/>
        Session_ID
        
        '''<remarks/>
        User_ID
        
        '''<remarks/>
        Store_No
        
        '''<remarks/>
        Device_ID
        
        '''<remarks/>
        Line_No
        
        '''<remarks/>
        Label_Code
        
        '''<remarks/>
        Barcode_No
        
        '''<remarks/>
        Description
        
        '''<remarks/>
        Quantity
        
        '''<remarks/>
        Item_No
        
        '''<remarks/>
        Unit_Of_Measure
        
        '''<remarks/>
        [Variant]
        
        '''<remarks/>
        Text_1
        
        '''<remarks/>
        Text_2
        
        '''<remarks/>
        Text_3
        
        '''<remarks/>
        Packed_Date
        
        '''<remarks/>
        Expiry_Date
        
        '''<remarks/>
        Time_Scanned
        
        '''<remarks/>
        Printed
        
        '''<remarks/>
        Date_Last_Printed
        
        '''<remarks/>
        Time_Last_Printed
    End Enum
End Namespace
