'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9043
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9043.
'
Namespace PrintUtilCU
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PrintUtilCU_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU")>  _
    Partial Public Class PrintUtilCU
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.1.100.22:7047/ABRWEB/WS/Bsat%20Supermarket%20S.A.L/Codeunit/PrintUtilCU"& _ 
                ""
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:WebDevicePrint", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="WebDevicePrint_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebDevicePrint(ByVal sessionID As String, ByRef userID As String, ByVal storeNo As String, ByVal deviceID As String, ByVal printerNameDc As String, ByVal printerIP As String, ByVal printerPortIn As String) As <System.Xml.Serialization.XmlElementAttribute("return_value")> Integer
            Dim results() As Object = Me.Invoke("WebDevicePrint", New Object() {sessionID, userID, storeNo, deviceID, printerNameDc, printerIP, printerPortIn})
            userID = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginWebDevicePrint(ByVal sessionID As String, ByVal userID As String, ByVal storeNo As String, ByVal deviceID As String, ByVal printerNameDc As String, ByVal printerIP As String, ByVal printerPortIn As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("WebDevicePrint", New Object() {sessionID, userID, storeNo, deviceID, printerNameDc, printerIP, printerPortIn}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndWebDevicePrint(ByVal asyncResult As System.IAsyncResult, ByRef userID As String) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            userID = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:InitPrint", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="InitPrint_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub InitPrint(ByVal labelCode As String)
            Me.Invoke("InitPrint", New Object() {labelCode})
        End Sub
        
        '''<remarks/>
        Public Function BeginInitPrint(ByVal labelCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("InitPrint", New Object() {labelCode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndInitPrint(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:WriteLine", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="WriteLine_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub WriteLine(ByVal ePL_Line As String)
            Me.Invoke("WriteLine", New Object() {ePL_Line})
        End Sub
        
        '''<remarks/>
        Public Function BeginWriteLine(ByVal ePL_Line As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("WriteLine", New Object() {ePL_Line}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndWriteLine(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:PrintLine", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="PrintLine_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PrintLine(ByVal ePL_Line As String)
            Me.Invoke("PrintLine", New Object() {ePL_Line})
        End Sub
        
        '''<remarks/>
        Public Function BeginPrintLine(ByVal ePL_Line As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintLine", New Object() {ePL_Line}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndPrintLine(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:AlignAmount", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="AlignAmount_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlignAmount(ByVal amount As Integer) As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("AlignAmount", New Object() {amount})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginAlignAmount(ByVal amount As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AlignAmount", New Object() {amount}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAlignAmount(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:AlignAmountLL", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="AlignAmountLL_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlignAmountLL(ByVal amount As Integer) As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("AlignAmountLL", New Object() {amount})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginAlignAmountLL(ByVal amount As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AlignAmountLL", New Object() {amount}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAlignAmountLL(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:AlignAmountDes", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="AlignAmountDes_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlignAmountDes(ByVal charCount As Integer, ByVal type As Integer) As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("AlignAmountDes", New Object() {charCount, type})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginAlignAmountDes(ByVal charCount As Integer, ByVal type As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AlignAmountDes", New Object() {charCount, type}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAlignAmountDes(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:GetBarcodeType", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="GetBarcodeType_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetBarcodeType(ByVal barcodeNo As String) As <System.Xml.Serialization.XmlElementAttribute("return_value")> String
            Dim results() As Object = Me.Invoke("GetBarcodeType", New Object() {barcodeNo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetBarcodeType(ByVal barcodeNo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetBarcodeType", New Object() {barcodeNo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetBarcodeType(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:Code2Int", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="Code2Int_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Code2Int(ByVal pCode As String) As <System.Xml.Serialization.XmlElementAttribute("return_value")> Integer
            Dim results() As Object = Me.Invoke("Code2Int", New Object() {pCode})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginCode2Int(ByVal pCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Code2Int", New Object() {pCode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCode2Int(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:UpdateLabelStatus", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="UpdateLabelStatus_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateLabelStatus()
            Me.Invoke("UpdateLabelStatus", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateLabelStatus(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateLabelStatus", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateLabelStatus(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:SaveLine", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="SaveLine_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SaveLine(ByVal ePL_Line As String)
            Me.Invoke("SaveLine", New Object() {ePL_Line})
        End Sub
        
        '''<remarks/>
        Public Function BeginSaveLine(ByVal ePL_Line As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SaveLine", New Object() {ePL_Line}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndSaveLine(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU:CloseFile", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", ResponseElementName:="CloseFile_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/PrintUtilCU", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CloseFile()
            Me.Invoke("CloseFile", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Function BeginCloseFile(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CloseFile", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndCloseFile(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
    End Class
End Namespace
