'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9043
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9043.
'
Namespace PricingJobHeaderPage
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PricingJobHeaderPage_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage")>  _
    Partial Public Class PricingJobHeaderPage_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.1.100.22:7047/ABRWEB/WS/Bsat%20Supermarket%20S.A.L/Page/PricingJobHeade"& _ 
                "rPage"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal No As String) As <System.Xml.Serialization.XmlElementAttribute("PricingJobHeaderPage")> PricingJobHeaderPage
            Dim results() As Object = Me.Invoke("Read", New Object() {No})
            Return CType(results(0),PricingJobHeaderPage)
        End Function
        
        '''<remarks/>
        Public Function BeginRead(ByVal No As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Read", New Object() {No}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRead(ByVal asyncResult As System.IAsyncResult) As PricingJobHeaderPage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PricingJobHeaderPage)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("PricingJobHeaderPage")> PricingJobHeaderPage
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),PricingJobHeaderPage)
        End Function
        
        '''<remarks/>
        Public Function BeginReadByRecId(ByVal recId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReadByRecId", New Object() {recId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndReadByRecId(ByVal asyncResult As System.IAsyncResult) As PricingJobHeaderPage
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PricingJobHeaderPage)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As PricingJobHeaderPage_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> PricingJobHeaderPage()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),PricingJobHeaderPage())
        End Function
        
        '''<remarks/>
        Public Function BeginReadMultiple(ByVal filter() As PricingJobHeaderPage_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndReadMultiple(ByVal asyncResult As System.IAsyncResult) As PricingJobHeaderPage()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PricingJobHeaderPage())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginIsUpdated(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("IsUpdated", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndIsUpdated(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetRecIdFromKey(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetRecIdFromKey", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetRecIdFromKey(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:Create", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="Create_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Create(ByRef PricingJobHeaderPage As PricingJobHeaderPage)
            Dim results() As Object = Me.Invoke("Create", New Object() {PricingJobHeaderPage})
            PricingJobHeaderPage = CType(results(0),PricingJobHeaderPage)
        End Sub
        
        '''<remarks/>
        Public Function BeginCreate(ByVal PricingJobHeaderPage As PricingJobHeaderPage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Create", New Object() {PricingJobHeaderPage}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndCreate(ByVal asyncResult As System.IAsyncResult, ByRef PricingJobHeaderPage As PricingJobHeaderPage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            PricingJobHeaderPage = CType(results(0),PricingJobHeaderPage)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:CreateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="CreateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef PricingJobHeaderPage_List() As PricingJobHeaderPage)
            Dim results() As Object = Me.Invoke("CreateMultiple", New Object() {PricingJobHeaderPage_List})
            PricingJobHeaderPage_List = CType(results(0),PricingJobHeaderPage())
        End Sub
        
        '''<remarks/>
        Public Function BeginCreateMultiple(ByVal PricingJobHeaderPage_List() As PricingJobHeaderPage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateMultiple", New Object() {PricingJobHeaderPage_List}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndCreateMultiple(ByVal asyncResult As System.IAsyncResult, ByRef PricingJobHeaderPage_List() As PricingJobHeaderPage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            PricingJobHeaderPage_List = CType(results(0),PricingJobHeaderPage())
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef PricingJobHeaderPage As PricingJobHeaderPage)
            Dim results() As Object = Me.Invoke("Update", New Object() {PricingJobHeaderPage})
            PricingJobHeaderPage = CType(results(0),PricingJobHeaderPage)
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdate(ByVal PricingJobHeaderPage As PricingJobHeaderPage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Update", New Object() {PricingJobHeaderPage}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdate(ByVal asyncResult As System.IAsyncResult, ByRef PricingJobHeaderPage As PricingJobHeaderPage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            PricingJobHeaderPage = CType(results(0),PricingJobHeaderPage)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef PricingJobHeaderPage_List() As PricingJobHeaderPage)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {PricingJobHeaderPage_List})
            PricingJobHeaderPage_List = CType(results(0),PricingJobHeaderPage())
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateMultiple(ByVal PricingJobHeaderPage_List() As PricingJobHeaderPage, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateMultiple", New Object() {PricingJobHeaderPage_List}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateMultiple(ByVal asyncResult As System.IAsyncResult, ByRef PricingJobHeaderPage_List() As PricingJobHeaderPage)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            PricingJobHeaderPage_List = CType(results(0),PricingJobHeaderPage())
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pricingjobheaderpage:Delete", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", ResponseElementName:="Delete_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginDelete(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Delete", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndDelete(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage")>  _
    Partial Public Class PricingJobHeaderPage
        
        Private keyField As String
        
        Private noField As String
        
        Private statusField As Status
        
        Private statusFieldSpecified As Boolean
        
        Private key1Field As String
        
        Private key_DescriptionField As String
        
        Private priorityField As Priority
        
        Private priorityFieldSpecified As Boolean
        
        Private no_of_LinesField As Integer
        
        Private no_of_LinesFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property No() As String
            Get
                Return Me.noField
            End Get
            Set
                Me.noField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StatusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Key", Order:=3)>  _
        Public Property Key1() As String
            Get
                Return Me.key1Field
            End Get
            Set
                Me.key1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Key_Description() As String
            Get
                Return Me.key_DescriptionField
            End Get
            Set
                Me.key_DescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Priority() As Priority
            Get
                Return Me.priorityField
            End Get
            Set
                Me.priorityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PrioritySpecified() As Boolean
            Get
                Return Me.priorityFieldSpecified
            End Get
            Set
                Me.priorityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property No_of_Lines() As Integer
            Get
                Return Me.no_of_LinesField
            End Get
            Set
                Me.no_of_LinesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property No_of_LinesSpecified() As Boolean
            Get
                Return Me.no_of_LinesFieldSpecified
            End Get
            Set
                Me.no_of_LinesFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage")>  _
    Public Enum Status
        
        '''<remarks/>
        Open
        
        '''<remarks/>
        Started
        
        '''<remarks/>
        Incomplete
        
        '''<remarks/>
        Finished
        
        '''<remarks/>
        Closed_Partial
        
        '''<remarks/>
        Closed_Ok
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage")>  _
    Public Enum Priority
        
        '''<remarks/>
        A
        
        '''<remarks/>
        B
        
        '''<remarks/>
        C
    End Enum
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage")>  _
    Partial Public Class PricingJobHeaderPage_Filter
        
        Private fieldField As PricingJobHeaderPage_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As PricingJobHeaderPage_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pricingjobheaderpage")>  _
    Public Enum PricingJobHeaderPage_Fields
        
        '''<remarks/>
        No
        
        '''<remarks/>
        Status
        
        '''<remarks/>
        Key
        
        '''<remarks/>
        Key_Description
        
        '''<remarks/>
        Priority
        
        '''<remarks/>
        No_of_Lines
    End Enum
End Namespace
