'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9043
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9043.
'
Namespace PRHead
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PRHeadAPI_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Partial Public Class PRHeadAPI_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.1.100.22:7047/ABRWEB/WS/Bsat%20Supermarket%20S.A.L/Page/PRHeadAPI"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal No As String) As <System.Xml.Serialization.XmlElementAttribute("PRHeadAPI")> PRHeadAPI
            Dim results() As Object = Me.Invoke("Read", New Object() {No})
            Return CType(results(0),PRHeadAPI)
        End Function
        
        '''<remarks/>
        Public Function BeginRead(ByVal No As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Read", New Object() {No}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRead(ByVal asyncResult As System.IAsyncResult) As PRHeadAPI
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PRHeadAPI)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("PRHeadAPI")> PRHeadAPI
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),PRHeadAPI)
        End Function
        
        '''<remarks/>
        Public Function BeginReadByRecId(ByVal recId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReadByRecId", New Object() {recId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndReadByRecId(ByVal asyncResult As System.IAsyncResult) As PRHeadAPI
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PRHeadAPI)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As PRHeadAPI_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> PRHeadAPI()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),PRHeadAPI())
        End Function
        
        '''<remarks/>
        Public Function BeginReadMultiple(ByVal filter() As PRHeadAPI_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndReadMultiple(ByVal asyncResult As System.IAsyncResult) As PRHeadAPI()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PRHeadAPI())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginIsUpdated(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("IsUpdated", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndIsUpdated(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetRecIdFromKey(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetRecIdFromKey", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetRecIdFromKey(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:Create", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="Create_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Create(ByRef PRHeadAPI As PRHeadAPI)
            Dim results() As Object = Me.Invoke("Create", New Object() {PRHeadAPI})
            PRHeadAPI = CType(results(0),PRHeadAPI)
        End Sub
        
        '''<remarks/>
        Public Function BeginCreate(ByVal PRHeadAPI As PRHeadAPI, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Create", New Object() {PRHeadAPI}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndCreate(ByVal asyncResult As System.IAsyncResult, ByRef PRHeadAPI As PRHeadAPI)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            PRHeadAPI = CType(results(0),PRHeadAPI)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:CreateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="CreateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef PRHeadAPI_List() As PRHeadAPI)
            Dim results() As Object = Me.Invoke("CreateMultiple", New Object() {PRHeadAPI_List})
            PRHeadAPI_List = CType(results(0),PRHeadAPI())
        End Sub
        
        '''<remarks/>
        Public Function BeginCreateMultiple(ByVal PRHeadAPI_List() As PRHeadAPI, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateMultiple", New Object() {PRHeadAPI_List}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndCreateMultiple(ByVal asyncResult As System.IAsyncResult, ByRef PRHeadAPI_List() As PRHeadAPI)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            PRHeadAPI_List = CType(results(0),PRHeadAPI())
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef PRHeadAPI As PRHeadAPI)
            Dim results() As Object = Me.Invoke("Update", New Object() {PRHeadAPI})
            PRHeadAPI = CType(results(0),PRHeadAPI)
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdate(ByVal PRHeadAPI As PRHeadAPI, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Update", New Object() {PRHeadAPI}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdate(ByVal asyncResult As System.IAsyncResult, ByRef PRHeadAPI As PRHeadAPI)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            PRHeadAPI = CType(results(0),PRHeadAPI)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef PRHeadAPI_List() As PRHeadAPI)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {PRHeadAPI_List})
            PRHeadAPI_List = CType(results(0),PRHeadAPI())
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateMultiple(ByVal PRHeadAPI_List() As PRHeadAPI, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateMultiple", New Object() {PRHeadAPI_List}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateMultiple(ByVal asyncResult As System.IAsyncResult, ByRef PRHeadAPI_List() As PRHeadAPI)
            Dim results() As Object = Me.EndInvoke(asyncResult)
            PRHeadAPI_List = CType(results(0),PRHeadAPI())
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/prheadapi:Delete", RequestNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", ResponseElementName:="Delete_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/prheadapi", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginDelete(ByVal Key As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Delete", New Object() {Key}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndDelete(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Partial Public Class PRHeadAPI
        
        Private keyField As String
        
        Private noField As String
        
        Private receivingField As Receiving
        
        Private receivingFieldSpecified As Boolean
        
        Private pickingField As Picking
        
        Private pickingFieldSpecified As Boolean
        
        Private counting_TypeField As Counting_Type
        
        Private counting_TypeFieldSpecified As Boolean
        
        Private reference_NoField As String
        
        Private reference_NameField As String
        
        Private typeField As Type
        
        Private typeFieldSpecified As Boolean
        
        Private storeField As String
        
        Private locationField As String
        
        Private rF_IDField As String
        
        Private rF_StatusField As RF_Status
        
        Private rF_StatusFieldSpecified As Boolean
        
        Private rF_Start_TimeField As Date
        
        Private rF_Start_TimeFieldSpecified As Boolean
        
        Private rF_End_TimeField As Date
        
        Private rF_End_TimeFieldSpecified As Boolean
        
        Private expected_DateField As Date
        
        Private expected_DateFieldSpecified As Boolean
        
        Private counted_DateField As Date
        
        Private counted_DateFieldSpecified As Boolean
        
        Private statusField As Status
        
        Private statusFieldSpecified As Boolean
        
        Private vendor_Invoice_NoField As String
        
        Private inventory_Terminal_AssignedField As String
        
        Private no_of_LinesField As Integer
        
        Private no_of_LinesFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property No() As String
            Get
                Return Me.noField
            End Get
            Set
                Me.noField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Receiving() As Receiving
            Get
                Return Me.receivingField
            End Get
            Set
                Me.receivingField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ReceivingSpecified() As Boolean
            Get
                Return Me.receivingFieldSpecified
            End Get
            Set
                Me.receivingFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Picking() As Picking
            Get
                Return Me.pickingField
            End Get
            Set
                Me.pickingField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PickingSpecified() As Boolean
            Get
                Return Me.pickingFieldSpecified
            End Get
            Set
                Me.pickingFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Counting_Type() As Counting_Type
            Get
                Return Me.counting_TypeField
            End Get
            Set
                Me.counting_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Counting_TypeSpecified() As Boolean
            Get
                Return Me.counting_TypeFieldSpecified
            End Get
            Set
                Me.counting_TypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reference_No() As String
            Get
                Return Me.reference_NoField
            End Get
            Set
                Me.reference_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reference_Name() As String
            Get
                Return Me.reference_NameField
            End Get
            Set
                Me.reference_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As Type
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TypeSpecified() As Boolean
            Get
                Return Me.typeFieldSpecified
            End Get
            Set
                Me.typeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Store() As String
            Get
                Return Me.storeField
            End Get
            Set
                Me.storeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Location() As String
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RF_ID() As String
            Get
                Return Me.rF_IDField
            End Get
            Set
                Me.rF_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RF_Status() As RF_Status
            Get
                Return Me.rF_StatusField
            End Get
            Set
                Me.rF_StatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RF_StatusSpecified() As Boolean
            Get
                Return Me.rF_StatusFieldSpecified
            End Get
            Set
                Me.rF_StatusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RF_Start_Time() As Date
            Get
                Return Me.rF_Start_TimeField
            End Get
            Set
                Me.rF_Start_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RF_Start_TimeSpecified() As Boolean
            Get
                Return Me.rF_Start_TimeFieldSpecified
            End Get
            Set
                Me.rF_Start_TimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RF_End_Time() As Date
            Get
                Return Me.rF_End_TimeField
            End Get
            Set
                Me.rF_End_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RF_End_TimeSpecified() As Boolean
            Get
                Return Me.rF_End_TimeFieldSpecified
            End Get
            Set
                Me.rF_End_TimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Expected_Date() As Date
            Get
                Return Me.expected_DateField
            End Get
            Set
                Me.expected_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Expected_DateSpecified() As Boolean
            Get
                Return Me.expected_DateFieldSpecified
            End Get
            Set
                Me.expected_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Counted_Date() As Date
            Get
                Return Me.counted_DateField
            End Get
            Set
                Me.counted_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Counted_DateSpecified() As Boolean
            Get
                Return Me.counted_DateFieldSpecified
            End Get
            Set
                Me.counted_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StatusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Vendor_Invoice_No() As String
            Get
                Return Me.vendor_Invoice_NoField
            End Get
            Set
                Me.vendor_Invoice_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Inventory_Terminal_Assigned() As String
            Get
                Return Me.inventory_Terminal_AssignedField
            End Get
            Set
                Me.inventory_Terminal_AssignedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property No_of_Lines() As Integer
            Get
                Return Me.no_of_LinesField
            End Get
            Set
                Me.no_of_LinesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property No_of_LinesSpecified() As Boolean
            Get
                Return Me.no_of_LinesFieldSpecified
            End Get
            Set
                Me.no_of_LinesFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Public Enum Receiving
        
        '''<remarks/>
        Purchase_Order
        
        '''<remarks/>
        Sales_Return_Order
        
        '''<remarks/>
        Transfer_In
        
        '''<remarks/>
        Purchase_Order_create
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Public Enum Picking
        
        '''<remarks/>
        Sales_Order
        
        '''<remarks/>
        Purchase_Return_Order
        
        '''<remarks/>
        Transfer_Out
        
        '''<remarks/>
        Sales_Order_create
        
        '''<remarks/>
        Purchase_Return_Order_create
        
        '''<remarks/>
        Transfer_Out_create
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Public Enum Counting_Type
        
        '''<remarks/>
        Receiving
        
        '''<remarks/>
        Picking
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Public Enum Type
        
        '''<remarks/>
        Scanned
        
        '''<remarks/>
        Leading
        
        '''<remarks/>
        Not_Used
        
        '''<remarks/>
        Difference_Entered
        
        '''<remarks/>
        No_Action
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Public Enum RF_Status
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Started
        
        '''<remarks/>
        Finished
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Public Enum Status
        
        '''<remarks/>
        Not_Confirmed
        
        '''<remarks/>
        Ok
        
        '''<remarks/>
        [Error]
        
        '''<remarks/>
        Re_Check
        
        '''<remarks/>
        Price_Difference
    End Enum
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Partial Public Class PRHeadAPI_Filter
        
        Private fieldField As PRHeadAPI_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As PRHeadAPI_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/prheadapi")>  _
    Public Enum PRHeadAPI_Fields
        
        '''<remarks/>
        No
        
        '''<remarks/>
        Receiving
        
        '''<remarks/>
        Picking
        
        '''<remarks/>
        Counting_Type
        
        '''<remarks/>
        Reference_No
        
        '''<remarks/>
        Reference_Name
        
        '''<remarks/>
        Type
        
        '''<remarks/>
        Store
        
        '''<remarks/>
        Location
        
        '''<remarks/>
        RF_ID
        
        '''<remarks/>
        RF_Status
        
        '''<remarks/>
        RF_Start_Time
        
        '''<remarks/>
        RF_End_Time
        
        '''<remarks/>
        Expected_Date
        
        '''<remarks/>
        Counted_Date
        
        '''<remarks/>
        Status
        
        '''<remarks/>
        Vendor_Invoice_No
        
        '''<remarks/>
        Inventory_Terminal_Assigned
        
        '''<remarks/>
        No_of_Lines
    End Enum
End Namespace
